<?php
namespace Heystack\Subsystem\Deals\Test;

use Heystack\Subsystem\Deals\Condition\EndDate;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-25 at 16:49:07.
 */
class EndDateTest extends \PHPUnit_Framework_TestCase
{

    protected $timeCondition;
    protected $adaptableConfigurationStub;

    protected function setUp()
    {
        $this->adaptableConfigurationStub = $this->getMockBuilder('Heystack\Subsystem\Deals\AdaptableConfiguration')
            ->disableOriginalConstructor()
            ->getMock();
    }

    protected function configureStub($getConfigMap, $hasConfigMap)
    {
        $this->adaptableConfigurationStub->expects($this->any())
            ->method('getConfig')
            ->will(
                $this->returnValueMap($getConfigMap)
            );

        $this->adaptableConfigurationStub->expects($this->any())
            ->method('hasConfig')
            ->will(
                $this->returnValueMap($hasConfigMap)
            );

        $this->timeCondition = new EndDate($this->adaptableConfigurationStub);
    }

    public function testIncorrectConfiguration()
    {
        $this->setExpectedException('Exception');

        $this->configureStub(
            [
                [

                ]
            ],
            [
                [

                ]
            ]
        );

    }

    public function testSetCurrentTime()
    {
        $this->configureStub(
            [
                [
                    'end', date(EndDate::$time_format)
                ]
            ],
            [
                [
                    'end', date(EndDate::$time_format)
                ]
            ]
        );


        $time = date(EndDate::$time_format);
        $this->timeCondition->setCurrentTime($time);
        $this->assertAttributeNotEmpty('currentTime', $this->timeCondition);

        return $time;
    }


    /**
     * @depends testSetCurrentTime
     */
    public function testGetCurrentTime($currentTime)
    {
        $this->configureStub(
            [
                [
                    'end', date(EndDate::$time_format)
                ]
            ],
            [
                [
                    'end', date(EndDate::$time_format)
                ]
            ]
        );


        $this->assertEquals($currentTime, date(EndDate::$time_format, $this->timeCondition->getCurrentTime()));

    }

    public function testGetDescription()
    {
        $this->configureStub(
            [
                [
                    'end', date(EndDate::$time_format)
                ]
            ],
            [
                [
                    'end', date(EndDate::$time_format)
                ]
            ]
        );

        $this->assertEquals(
            $this->timeCondition->getDescription(),
            'Valid if current date less than: ' . date(EndDate::$time_format)
        );

    }

    public function testGetType()
    {
        $this->configureStub(
            [
                [
                    'end', date(EndDate::$time_format)
                ]
            ],
            [
                [
                    'end', date(EndDate::$time_format)
                ]
            ]
        );

        $this->assertEquals($this->timeCondition->getType(), EndDate::CONDITION_TYPE);
    }

    /**
     * @depends testSetCurrentTime
     */
    public function testMet()
    {
        $this->configureStub(
            [
                [
                    'end', date(EndDate::$time_format, strtotime('tomorrow'))
                ]
            ],
            [
                [
                    'end', date(EndDate::$time_format, strtotime('tomorrow'))
                ]
            ]
        );

        $this->assertTrue($this->timeCondition->met());
    }

    /**
     * @depends testSetCurrentTime
     */
    public function testAlmostMet()
    {
        $this->configureStub(
            [
                [
                    'end', date(EndDate::$time_format, strtotime('tomorrow'))
                ]
            ],
            [
                [
                    'end', date(EndDate::$time_format, strtotime('tomorrow'))
                ]
            ]
        );

        $this->assertTrue($this->timeCondition->almostMet());
    }

}
