<?php
namespace Heystack\Deals\Test;

use Heystack\Deals\Condition\PurchasableHasQuantityInCart;
use Heystack\Products\ProductHolder\PurchasableHolder;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-25 at 16:49:07.
 */
class PurchasableHasQuantityInCartTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Time
     */
    protected $purchasableQuantityInCartCondition;
    protected $adaptableConfigurationStub;
    protected $purchaseableHolder;
    protected $purchasable;
    protected $testProduct;
    protected $testProductTwo;

    protected function setUp()
    {
        $this->adaptableConfigurationStub = $this->getMockBuilder('Heystack\Deals\AdaptableConfiguration')
            ->disableOriginalConstructor()
            ->getMock();

        $this->purchaseableHolder = $this->getMockBuilder('Heystack\Products\ProductHolder\ProductHolder')
            ->disableOriginalConstructor()
            ->getMock();

        $this->purchasable = $this->getMockBuilder('Heystack\Ecommerce\Purchasable\Interfaces\PurchasableInterface')
            ->getMock();

    }

    protected function configureStub($getConfigMap, $hasConfigMap)
    {
        $this->adaptableConfigurationStub->expects($this->any())
            ->method('getConfig')
            ->will(
                $this->returnValueMap($getConfigMap)
            );

        $this->adaptableConfigurationStub->expects($this->any())
            ->method('hasConfig')
            ->will(
                $this->returnValueMap($hasConfigMap)
            );

        $this->purchasableQuantityInCartCondition = new PurchasableHasQuantityInCart($this->purchaseableHolder, $this->adaptableConfigurationStub);
    }

    public function testNoConfiguration()
    {
        $this->setExpectedException('Exception');

        $this->configureStub(
            [
                [

                ]
            ],
            [
                [

                ]
            ]
        );
    }

    public function testConfiguration()
    {
        $this->configureStub(
            [
                [
                    PurchasableHasQuantityInCart::MINIMUM_QUANTITY_KEY, 1
                ],
                [
                    PurchasableHasQuantityInCart::PURCHASABLE_IDENTIFIERS, [1]
                ]
            ],
            [
                [
                    PurchasableHasQuantityInCart::MINIMUM_QUANTITY_KEY, 1
                ],
                [
                    PurchasableHasQuantityInCart::PURCHASABLE_IDENTIFIERS, [1]
                ]
            ]
        );
    }

    public function testNoPurchasableIdentifiersConfiguration()
    {
        $this->setExpectedException('Exception');

        $this->configureStub(
            [
                [
                    PurchasableHasQuantityInCart::MINIMUM_QUANTITY_KEY, 1
                ]
            ],
            [
                [
                    PurchasableHasQuantityInCart::MINIMUM_QUANTITY_KEY, 1
                ]
            ]
        );
    }

    public function testNoMinimumQuantityConfiguration()
    {
        $this->setExpectedException('Exception');

        $this->configureStub(
            [
                [
                    PurchasableHasQuantityInCart::PURCHASABLE_IDENTIFIERS, [1]
                ]
            ],
            [
                [
                    PurchasableHasQuantityInCart::PURCHASABLE_IDENTIFIERS, [1]
                ]
            ]
        );
    }

    public function testGetType()
    {
        $this->configureStub(
            [
                [
                    PurchasableHasQuantityInCart::MINIMUM_QUANTITY_KEY, 1
                ],
                [
                    PurchasableHasQuantityInCart::PURCHASABLE_IDENTIFIERS, [1]
                ]
            ],
            [
                [
                    PurchasableHasQuantityInCart::MINIMUM_QUANTITY_KEY, 1
                ],
                [
                    PurchasableHasQuantityInCart::PURCHASABLE_IDENTIFIERS, [1]
                ]
            ]
        );

        $this->assertEquals($this->purchasableQuantityInCartCondition->getType(), PurchasableHasQuantityInCart::CONDITION_TYPE);
    }

    public function testGetDescription()
    {
        $this->configureStub(
            [
                [
                    PurchasableHasQuantityInCart::MINIMUM_QUANTITY_KEY, 1
                ],
                [
                    PurchasableHasQuantityInCart::PURCHASABLE_IDENTIFIERS, [1]
                ]
            ],
            [
                [
                    PurchasableHasQuantityInCart::MINIMUM_QUANTITY_KEY, 1
                ],
                [
                    PurchasableHasQuantityInCart::PURCHASABLE_IDENTIFIERS, [1]
                ]
            ]
        );

        $this->purchasableQuantityInCartCondition->setMinimumQuantity(4);
        $this->purchasableQuantityInCartCondition->setPurchasableIdentifiers([4]);

        $this->assertEquals($this->purchasableQuantityInCartCondition->getDescription(), 'One of them items must have at least ' . $this->purchasableQuantityInCartCondition->getMinimumQuantity() . ' quantity in the cart. Items include ' . implode($this->purchasableQuantityInCartCondition->getPurchasableIdentifiers(), ','));


    }

    public function testMet()
    {
        $this->testProduct = $this->getMockBuilder('Heystack\Deals\Interfaces\DealPurchasableInterface')
            ->disableOriginalConstructor()
            ->getMock();

        $this->testProductTwo = $this->getMockBuilder('Heystack\Deals\Interfaces\DealPurchasableInterface')
            ->disableOriginalConstructor()
            ->getMock();

        $this->testProduct->expects($this->any())
            ->method('getQuantity')
            ->will($this->returnValue(1));

        $this->testProduct->expects($this->any())
            ->method('hasFreeItems')
            ->will($this->returnValue(false));

        $this->testProductTwo->expects($this->any())
            ->method('getQuantity')
            ->will($this->returnValue(5));

        $this->testProductTwo->expects($this->any())
            ->method('hasFreeItems')
            ->will($this->returnValue(true));

        $this->testProductTwo->expects($this->any())
            ->method('getFreeQuantity')
            ->will($this->returnValue(1));

        $this->testProductTwo->expects($this->any())
            ->method('getUnitPrice')
            ->will($this->returnValue(10));

        $this->purchaseableHolder->expects($this->any())
            ->method('getPurchasablesByPrimaryIdentifier')
            ->will($this->returnValue([$this->testProduct, $this->testProductTwo]));

        $eventService = $this->getMockBuilder('Heystack\Core\EventDispatcher')
            ->disableOriginalConstructor()
            ->getMock();

        $this->purchaseableHolder->expects($this->any())
            ->method('getEventService')
            ->will($this->returnValue($eventService));

        $productOne = $this->getMockBuilder('Heystack\Core\Identifier\Identifier')
            ->setConstructorArgs([1])
            ->getMock();

        $productTwo = $this->getMockBuilder('Heystack\Core\Identifier\Identifier')
            ->setConstructorArgs([2])
            ->getMock();

        $this->configureStub(
            [
                [
                    PurchasableHasQuantityInCart::MINIMUM_QUANTITY_KEY, 5
                ],
                [
                    PurchasableHasQuantityInCart::PURCHASABLE_IDENTIFIERS, [$productOne, $productTwo]
                ]
            ],
            [
                [
                    PurchasableHasQuantityInCart::MINIMUM_QUANTITY_KEY, 5
                ],
                [
                    PurchasableHasQuantityInCart::PURCHASABLE_IDENTIFIERS, [$productOne, $productTwo]
                ]
            ]
        );

        $this->assertTrue($this->purchasableQuantityInCartCondition->met());


    }

    public function testAlmostMet()
    {
        $this->testProduct = $this->getMockBuilder('Heystack\Deals\Interfaces\DealPurchasableInterface')
            ->disableOriginalConstructor()
            ->getMock();

        $this->testProductTwo = $this->getMockBuilder('Heystack\Deals\Interfaces\DealPurchasableInterface')
            ->disableOriginalConstructor()
            ->getMock();

        $this->testProduct->expects($this->any())
            ->method('getQuantity')
            ->will($this->returnValue(1));

        $this->testProduct->expects($this->any())
            ->method('hasFreeItems')
            ->will($this->returnValue(false));

        $this->testProductTwo->expects($this->any())
            ->method('getQuantity')
            ->will($this->returnValue(5));

        $this->testProductTwo->expects($this->any())
            ->method('hasFreeItems')
            ->will($this->returnValue(true));

        $this->testProductTwo->expects($this->any())
            ->method('getFreeQuantity')
            ->will($this->returnValue(1));

        $this->testProductTwo->expects($this->any())
            ->method('getUnitPrice')
            ->will($this->returnValue(10));

        $this->purchaseableHolder->expects($this->any())
            ->method('getPurchasablesByPrimaryIdentifier')
            ->will($this->returnValue([$this->testProduct, $this->testProductTwo]));

        $eventService = $this->getMockBuilder('Heystack\Core\EventDispatcher')
            ->disableOriginalConstructor()
            ->getMock();

        $this->purchaseableHolder->expects($this->any())
            ->method('getEventService')
            ->will($this->returnValue($eventService));

        $productOne = $this->getMockBuilder('Heystack\Core\Identifier\Identifier')
            ->setConstructorArgs([1])
            ->getMock();

        $productTwo = $this->getMockBuilder('Heystack\Core\Identifier\Identifier')
            ->setConstructorArgs([2])
            ->getMock();

        $this->configureStub(
            [
                [
                    PurchasableHasQuantityInCart::MINIMUM_QUANTITY_KEY, 5
                ],
                [
                    PurchasableHasQuantityInCart::PURCHASABLE_IDENTIFIERS, [$productOne, $productTwo]
                ]
            ],
            [
                [
                    PurchasableHasQuantityInCart::MINIMUM_QUANTITY_KEY, 5
                ],
                [
                    PurchasableHasQuantityInCart::PURCHASABLE_IDENTIFIERS, [$productOne, $productTwo]
                ]
            ]
        );

        $this->assertTrue($this->purchasableQuantityInCartCondition->almostMet());
    }
}
