parameters:

  coupon_holder.class: Heystack\Deals\Coupon\CouponHolder
  coupon_input_processor.class: Heystack\Deals\Coupon\Input\Processor
  coupon_output_processor.class: Heystack\Deals\Coupon\Output\Processor

  deal.handler.class: Heystack\Deals\DealHandler

  deal.subscriber.class: Heystack\Deals\Subscriber

  deal.condition.configuration.class: Heystack\Deals\AdaptableConfiguration
  deal.condition.startdate.class: Heystack\Deals\Condition\StartDate
  deal.condition.enddate.class: Heystack\Deals\Condition\EndDate
  deal.condition.minimumcarttotal.class: Heystack\Deals\Condition\MinimumCartTotal
  deal.condition.quantityofpurchasablesincart.class: Heystack\Deals\Condition\QuantityOfPurchasablesInCart
  deal.condition.purchasablehasquantityincart.class: Heystack\Deals\Condition\PurchasableHasQuantityInCart
  deal.condition.hascoupon.class: Heystack\Deals\Condition\HasCoupon

  deal.result.configuration.class: Heystack\Deals\AdaptableConfiguration
  deal.result.freegift.class: Heystack\Deals\Result\FreeGift
  deal.result.shipping.class: Heystack\Deals\Result\Shipping
  deal.result.cartdiscount.class: Heystack\Deals\Result\CartDiscount
  deal.result.purchasablediscount.class: Heystack\Deals\Result\PurchasableDiscount
  deal.result.cheapestpurchasablediscount.class: Heystack\Deals\Result\CheapestPurchasableDiscount
  
  deals_subscriber.class: Heystack\Deals\DealsSubscriber
  deal_purchasable_subscriber.class: Heystack\Deals\PurchasableHolderSubscriber

services:
  deals_subscriber:
    class: %deals_subscriber.class%
    arguments: [@event_dispatcher]
    tags:
      - { name: event_dispatcher.subscriber }

  deal_purchasable_subscriber:
    class: %deal_purchasable_subscriber.class%
    tags:
      - { name: autoinject, setter: true }
      - { name: event_dispatcher.subscriber }

  coupon_holder:
    class: %coupon_holder.class%
    arguments: [@state, @event_dispatcher]
    tags:
      - { name: state.restore }
      - { name: autoinject.provides }

  coupon_input_processor:
    class: %coupon_input_processor.class%
    arguments: [ %coupon.class%, @coupon_holder ]
    tags:
      - { name: input_processor_handler.processor }

  coupon_output_procesor:
    class: %coupon_output_processor.class%
    arguments: [ %coupon.class% ]
    tags:
      - { name: output_processor_handler.processor }

  deals.deal_handler:
    class: %deal.handler.class%
    arguments: [ @state, @event_dispatcher, @currency_service ]
    abstract: true

  deals.subscriber:
    class: %deal.subscriber.class%
    arguments: [@event_dispatcher, @storage, @state, @coupon_holder]
    abstract: true

  deals.condition.configuration:
    class: %deal.condition.configuration.class%
    abstract: true

  deals.condition.startdate:
    class: %deal.condition.startdate.class%
    abstract: true

  deals.condition.enddate:
    class: %deal.condition.enddate.class%
    abstract: true

  deals.condition.hascoupon:
    class: %deal.condition.hascoupon.class%
    arguments: [ @coupon_holder ]
    abstract: true

  deals.condition.minimumcarttotal:
      class: %deal.condition.minimumcarttotal.class%
      arguments: [@purchasableholder, @currency_service]
      abstract: true

  deals.condition.quantityofpurchasablesincart:
      class: %deal.condition.quantityofpurchasablesincart.class%
      arguments: [@purchasableholder]
      abstract: true

  deals.condition.purchasablehasquantityincart:
      class: %deal.condition.purchasablehasquantityincart.class%
      arguments: [@purchasableholder]
      abstract: true

  deals.result.configuration:
    class: %deal.result.configuration.class%
    abstract: true

  deals.result.freegift:
    class: %deal.result.freegift.class%
    arguments: [@event_dispatcher, @purchasableholder, @currency_service]
    abstract: true

  deals.result.shipping:
    class: %deal.result.shipping.class%
    arguments: [@event_dispatcher, @shipping_service, @currency_service]
    abstract: true

  deals.result.cartdiscount:
    class: %deal.result.cartdiscount.class%
    arguments: [@event_dispatcher, @purchasableholder, @currency_service]
    abstract: true

  deals.result.purchasablediscount:
    class: %deal.result.purchasablediscount.class%
    arguments: [@event_dispatcher, @purchasableholder, @currency_service]
    abstract: true

  deals.result.cheapestpurchasablediscount:
    class: %deal.result.cheapestpurchasablediscount.class%
    arguments: [@event_dispatcher, @purchasableholder]
    abstract: true
    tags:
      - { name: set.currency_service }

  dealhandler_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-deals/config/storage/dealhandler.yml ]
    tags:
      - { name: schema }
      - { name: autoinject, arguments: true }

  transaction_dealhandler_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-deals/config/storage/transaction_dealhandler.yml ]
    tags:
      - { name: schema }
      - { name: autoinject, arguments: true }

  coupon_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-deals/config/storage/coupon.yml ]
    tags:
      - { name: schema }
      - { name: autoinject, arguments: true }

  dealhandler_coupon_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-deals/config/storage/dealhandler_coupon.yml ]
    tags:
      - { name: schema }
      - { name: autoinject, arguments: true }