parameters:

  deal.data.class: Deal

  deal.handler.class: Heystack\Subsystem\Deals\DealHandler

  deal.subscriber.class: Heystack\Subsystem\Deals\Subscriber

  deal.condition.configuration.class: Heystack\Subsystem\Deals\AdaptableConfiguration
  deal.condition.startdate.class: Heystack\Subsystem\Deals\Condition\StartDate
  deal.condition.enddate.class: Heystack\Subsystem\Deals\Condition\EndDate
  deal.condition.minimumcarttotal.class: Heystack\Subsystem\Deals\Condition\MinimumCartTotal
  deal.condition.quantityofpurchasablesincart.class: Heystack\Subsystem\Deals\Condition\QuantityOfPurchasablesInCart
  deal.condition.purchasablehasquantityincart.class: Heystack\Subsystem\Deals\Condition\PurchasableHasQuantityInCart

  deal.result.configuration.class: Heystack\Subsystem\Deals\AdaptableConfiguration
  deal.result.freegift.class: Heystack\Subsystem\Deals\Result\FreeGift
  deal.result.shipping.class: Heystack\Subsystem\Deals\Result\Shipping
  deal.result.cartdiscount.class: Heystack\Subsystem\Deals\Result\CartDiscount
  deal.result.purchasablediscount.class: Heystack\Subsystem\Deals\Result\PurchasableDiscount
  deal.result.cheapestpurchasablediscount.class: Heystack\Subsystem\Deals\Result\CheapestPurchasableDiscount

services:
  deals.deal_handler:
    class: %deal.handler.class%
    arguments: [@state, @event_dispatcher]
    abstract: true

  deals.subscriber:
    class: %deal.subscriber.class%
    arguments: [@event_dispatcher, @storage, @productholder]
    abstract: true

  deals.condition.configuration:
    class: %deal.condition.configuration.class%
    abstract: true

  deals.condition.startdate:
    class: %deal.condition.startdate.class%
    abstract: true

  deals.condition.enddate:
    class: %deal.condition.enddate.class%
    abstract: true

  deals.condition.minimumcarttotal:
      class: %deal.condition.minimumcarttotal.class%
      arguments: [@productholder, @currency_service]
      abstract: true

  deals.condition.quantityofpurchasablesincart:
      class: %deal.condition.quantityofpurchasablesincart.class%
      arguments: [@productholder]
      abstract: true

  deals.condition.purchasablehasquantityincart:
      class: %deal.condition.purchasablehasquantityincart.class%
      arguments: [@productholder]
      abstract: true

  deals.result.configuration:
    class: %deal.result.configuration.class%
    abstract: true

  deals.result.freegift:
    class: %deal.result.freegift.class%
    arguments: [@event_dispatcher, @productholder, @dataobject_handler]
    abstract: true

  deals.result.shipping:
    class: %deal.result.shipping.class%
    arguments: [@event_dispatcher, @shipping_service, @currency_service]
    abstract: true

  deals.result.cartdiscount:
    class: %deal.result.cartdiscount.class%
    arguments: [@event_dispatcher, @productholder, @currency_service]
    abstract: true

  deals.result.purchasablediscount:
    class: %deal.result.purchasablediscount.class%
    arguments: [@event_dispatcher, @productholder, @currency_service]
    abstract: true

  deals.result.cheapestpurchasablediscount:
    class: %deal.result.cheapestpurchasablediscount.class%
    arguments: [@event_dispatcher, @productholder]
    abstract: true

  dealhandler_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-deals/config/storage/dealhandler.yml, @state_global ]
    tags:
      - { name: dataobject_generator.schema }

  transaction_dealhandler_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-deals/config/storage/transaction_dealhandler.yml, @state_global ]
    tags:
      - { name: dataobject_generator.schema }