<?php
namespace Heystack\Deals\Test;

use Heystack\Deals\AdaptableConfiguration;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-25 at 16:49:03.
 */
class AdaptableConfigurationTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AdaptableConfiguration
     */
    protected $adaptableConfiguration;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->adaptableConfiguration = new AdaptableConfiguration(['test_identifier' => 'test_value']);
    }

    /**
     * @covers Heystack\Deals\AdaptableConfiguration::getConfig
     */
    public function testGetConfig()
    {
        $this->assertEquals(
            $this->adaptableConfiguration->getConfig('test_identifier'),
            'test_value'
        );
    }

    /**
     * @covers Heystack\Deals\AdaptableConfiguration::hasConfig
     */
    public function testHasConfig()
    {
        $this->assertTrue($this->adaptableConfiguration->hasConfig('test_identifier'));
    }
}
