<?php
namespace Heystack\Subsystem\Deals;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-25 at 16:49:12.
 */
class DealHandlerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DealHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new DealHandler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heystack\Subsystem\Deals\DealHandler::getPromotionalMessage
     * @todo   Implement testGetPromotionalMessage().
     */
    public function testGetPromotionalMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Deals\DealHandler::setResult
     * @todo   Implement testSetResult().
     */
    public function testSetResult()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Deals\DealHandler::addCondition
     * @todo   Implement testAddCondition().
     */
    public function testAddCondition()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Deals\DealHandler::getIdentifier
     * @todo   Implement testGetIdentifier().
     */
    public function testGetIdentifier()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Deals\DealHandler::getTotal
     * @todo   Implement testGetTotal().
     */
    public function testGetTotal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Deals\DealHandler::updateTotal
     * @todo   Implement testUpdateTotal().
     */
    public function testUpdateTotal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Deals\DealHandler::conditionsMet
     * @todo   Implement testConditionsMet().
     */
    public function testConditionsMet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Deals\DealHandler::getType
     * @todo   Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Deals\DealHandler::getStorableData
     * @todo   Implement testGetStorableData().
     */
    public function testGetStorableData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Deals\DealHandler::getStorableIdentifier
     * @todo   Implement testGetStorableIdentifier().
     */
    public function testGetStorableIdentifier()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Deals\DealHandler::getSchemaName
     * @todo   Implement testGetSchemaName().
     */
    public function testGetSchemaName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Deals\DealHandler::getStorableBackendIdentifiers
     * @todo   Implement testGetStorableBackendIdentifiers().
     */
    public function testGetStorableBackendIdentifiers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Deals\DealHandler::saveState
     * @todo   Implement testSaveState().
     */
    public function testSaveState()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Deals\DealHandler::restoreState
     * @todo   Implement testRestoreState().
     */
    public function testRestoreState()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Deals\DealHandler::serialize
     * @todo   Implement testSerialize().
     */
    public function testSerialize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Deals\DealHandler::unserialize
     * @todo   Implement testUnserialize().
     */
    public function testUnserialize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Deals\DealHandler::getParentReference
     * @todo   Implement testGetParentReference().
     */
    public function testGetParentReference()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heystack\Subsystem\Deals\DealHandler::setParentReference
     * @todo   Implement testSetParentReference().
     */
    public function testSetParentReference()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
